<a href="https://colab.research.google.com/github/MarioHenriqueUFAL/ProjetosBI/blob/main/projeto_comercial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

#Tratamento dos Dados

In [ ]:
df = pd.read_excel('/content/Dados_Comerciais.xlsx')

In [ ]:
df.head(20)

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
0,SKU-0000001,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2012-10-04,679.00,345
1,SKU-0000002,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-01-01,832.00,712
2,SKU-0000003,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2,2012-02-02,790.00,390
3,SKU-0000004,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-03-03,765.32,200
4,SKU-0000005,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Artur Moreira,1004,5,2012-04-04,459.89,234
5,SKU-0000006,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Rodrigo Fagundes,1005,4,2012-05-04,590.98,90
6,SKU-0000007,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-06-04,1000.91,134
7,SKU-0000008,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,A9990,Belo Horizonte,Minas Gerais,Fernando Zambrini,1007,2,2012-07-04,1229.00,800
8,SKU-0000009,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-08-04,1300.00,400
9,SKU-0000010,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,André Pereira,1002,4,2012-09-04,1290.00,600
10,SKU-0000011,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,5,2012-09-04,1287.00,560
11,SKU-0000012,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,A9990,Belo Horizonte,Minas Gerais,Josias Silva,1006,5,2012-11-04,1651.00,790
12,SKU-0000013,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,4,2012-11-04,1100.00,790
13,SKU-0000014,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-12-04,1190.00,790
14,SKU-0000015,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Artur Moreira,1004,2,2012-12-04,1190.98,790
15,SKU-0000016,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,A9990,Belo Horizonte,Minas Gerais,Rodrigo Fagundes,1005,4,2013-01-02,877.00,120
16,SKU-0000017,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,5,2013-02-02,982.00,120
17,SKU-0000018,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Fernando Zambrini,1007,6,2013-03-02,872.00,120
18,SKU-0000019,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,5,2013-04-02,799.00,120
19,SKU-0000020,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,André Pereira,1002,4,2013-05-02,899.00,120

#Tratamento dos dados da Tabela "Produtos"

Durante a análise da base de dados, observou-se que produtos idênticos tinham códigos diferentes. Dessa forma, a primeira coisa a ser feita foi modificar os códigos dos produtos, de modo a garantir que produtos idênticos tenham a mesma identificação na base de dados.

Na construção da modelagem do banco de dados, devemos garantir que cada produto seja identificado de maneira única a partir da utilização de uma chave primário. Para a tabela "produtos" a chave primária escolhida é a coluna "ID-Produto", por este motivo é imprescindível garantir que cada um dos produtos tenha uma identificação única, de modo a impedir redundâncias no banco de dados.

A primeira etapa consistiu na determinação de códigos únicos para cada tipo de produto. Em seguida, foram atribuídos códigos únicos para cada tipo de produto de acordo com o fabricante. Pois produtos do mesmo tipo podem ser fabricados por diferentes fabricantes, caracterizando diferença entre os produtos.

Verificando os valores únicos na coluna "categoria"

In [ ]:
df['Categoria'].unique()

array(['Celulares', 'Eletrodomésticos', 'Eletrônicos', 'Eletroportáteis'],
      dtype=object)

Identificando os diferentes tipos de produtos

In [ ]:
df['Produto'].unique()

array(['LG K10 TV Power', 'Geladeira Duplex', 'Lavadora 11 Kg',
       'Notebook Dell 8 GB', 'Desktop 32 GB', 'Desktop HP 16 GB',
       'Micro-Ondas', 'Grill', 'Forno-Micro-Ondas', 'Fritadeira',
       'Ar Condicionado', 'Aspirador', 'Impressora Deskjet',
       'Secadora Vapor', 'Samsung Galaxy 8', 'Sony Experia XA',
       'Morotola Moto G5', 'Ventilador', 'Processador de Alimentos',
       'Liquidificador'], dtype=object)

OS novos códigos de produtos deverão seguir a seguinte forma padrão: PROD-001-00

Após "PROD-" os três dígitos identificam o tipo do produto. Os últimos dois dígitos indicam, para o mesmo tipo do produto, o fabricante.

In [ ]:
produto = input('Digite o nome do produto: ')
df[df['Produto'] == produto]

Digite o nome do produto: Liquidificador

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
409,SKU-0000410,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Josias Silva,1006,2,2015-06-02,149.0,120
410,SKU-0000411,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Fernando Zambrini,1007,2,2015-07-02,149.0,120
411,SKU-0000412,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Josias Silva,1006,2,2015-08-02,149.0,120
412,SKU-0000413,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-09-02,149.0,120
413,SKU-0000414,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-10-02,149.0,120
414,SKU-0000415,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-11-02,149.0,120
415,SKU-0000416,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-12-02,121.0,120
416,SKU-0000417,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-01-02,121.0,120

In [ ]:
novo_codigo = input('Insira o novo código: ')
df.loc[df['Produto'] == produto, ['ID-Produto']] = novo_codigo
df[df['Produto'] == produto]

Insira o novo código: PROD-020-01

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
409,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Josias Silva,1006,2,2015-06-02,149.0,120
410,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Fernando Zambrini,1007,2,2015-07-02,149.0,120
411,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Josias Silva,1006,2,2015-08-02,149.0,120
412,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-09-02,149.0,120
413,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-10-02,149.0,120
414,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-11-02,149.0,120
415,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-12-02,121.0,120
416,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-01-02,121.0,120

Após essa etapa, cada tipo de produto possui uma identificação única

Verificando os códigos associados a cada tipo de produtos, temos:

In [ ]:
for i in df['Produto'].unique():
  print('Produto: '+i)
  print(df.loc[df['Produto'] == i,'ID-Produto'].unique())

Produto: LG K10 TV Power
['PROD-001-00']
Produto: Geladeira Duplex
['PROD-002-00' 'PROD-002-01' 'PROD-002-02' 'PROD-002-03']
Produto: Lavadora 11 Kg
['PROD-003-01' 'PROD-003-02']
Produto: Notebook Dell 8 GB
['PROD-004-01']
Produto: Desktop 32 GB
['PROD-005-01' 'PROD-005-02']
Produto: Desktop HP 16 GB
['PROD-006-01']
Produto: Micro-Ondas
['PROD-007-01' 'PROD-007-02' 'PROD-007-03']
Produto: Grill
['PROD-008-01' 'PROD-008-02']
Produto: Forno-Micro-Ondas
['PROD-009-01' 'PROD-009-02']
Produto: Fritadeira
['PROD-010-01' 'PROD-010-02']
Produto: Ar Condicionado
['PROD-011-01']
Produto: Aspirador
['PROD-012-01']
Produto: Impressora Deskjet
['PROD-013-01' 'PROD-013-02']
Produto: Secadora Vapor
['PROD-014-01']
Produto: Samsung Galaxy 8
['PROD-015-01']
Produto: Sony Experia XA
['PROD-016-01']
Produto: Morotola Moto G5
['PROD-017-01']
Produto: Ventilador
['PROD-018-01']
Produto: Processador de Alimentos
['PROD-019-01']
Produto: Liquidificador
['PROD-020-01']

Agora, prosseguimos para associação de um código único para cada tipo de produto e tipo de fabricante.

In [ ]:
codigo_produto = input('Digite o código do produto: ')
df[df['ID-Produto'] == codigo_produto]

Digite o código do produto: PROD-020-01

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
409,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Josias Silva,1006,2,2015-06-02,149.0,120
410,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Fernando Zambrini,1007,2,2015-07-02,149.0,120
411,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Josias Silva,1006,2,2015-08-02,149.0,120
412,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-09-02,149.0,120
413,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-10-02,149.0,120
414,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-11-02,149.0,120
415,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-12-02,121.0,120
416,PROD-020-01,Liquidificador,Eletroportáteis,Doméstico,Samsung,R1295,Rio de Janeiro,Rio de Janeiro,Rodrigo Fagundes,1005,2,2015-01-02,121.0,120

In [ ]:
df[df['ID-Produto'] == codigo_produto]['Fabricante'].unique()

array(['Samsung'], dtype=object)

In [ ]:
fabricante = input('Informe o nome do fabricante: ')
df[(df['ID-Produto'] == codigo_produto) & (df['Fabricante'] == fabricante)]

Informe o nome do fabricante: Epson

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
265,PROD-013-01,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2015-02-02,713.00,120
266,PROD-013-01,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-03-02,713.00,120
267,PROD-013-01,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,Maria Fernandes,1001,2,2015-04-02,713.00,120
268,PROD-013-01,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-05-02,713.00,120
269,PROD-013-01,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-06-02,713.00,120
270,PROD-013-01,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,Artur Moreira,1004,2,2015-07-02,456.00,120
271,PROD-013-01,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-08-02,713.00,120
272,PROD-013-01,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-09-02,713.00,120
273,PROD-013-01,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,Artur Moreira,1004,2,2015-10-02,765.34,120
274,PROD-013-01,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-11-02,713.00,120
275,PROD-013-01,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-12-02,713.00,120
276,PROD-013-01,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,Artur Moreira,1004,2,2015-01-02,234.12,120

In [ ]:
novo_codigo = input('Informe o novo código: ')
df.loc[(df['ID-Produto'] == codigo_produto) & (df['Fabricante'] == fabricante), 'ID-Produto'] = novo_codigo
df[(df['ID-Produto'] == novo_codigo) & (df['Fabricante'] == fabricante)]

Informe o novo código: PROD-013-02

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
265,PROD-013-02,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2015-02-02,713.00,120
266,PROD-013-02,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-03-02,713.00,120
267,PROD-013-02,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,Maria Fernandes,1001,2,2015-04-02,713.00,120
268,PROD-013-02,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-05-02,713.00,120
269,PROD-013-02,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-06-02,713.00,120
270,PROD-013-02,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,Artur Moreira,1004,2,2015-07-02,456.00,120
271,PROD-013-02,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-08-02,713.00,120
272,PROD-013-02,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-09-02,713.00,120
273,PROD-013-02,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,Artur Moreira,1004,2,2015-10-02,765.34,120
274,PROD-013-02,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-11-02,713.00,120
275,PROD-013-02,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,André Pereira,1002,2,2015-12-02,713.00,120
276,PROD-013-02,Impressora Deskjet,Eletrônicos,Doméstico,Epson,SP8821,São Paulo,São Paulo,Artur Moreira,1004,2,2015-01-02,234.12,120

Verificando se para cada tipo de produto o valor da coluna "Categoria" é único.

In [ ]:
for i in df['Produto'].unique():
  print('Produto: '+i)
  print(df[df['Produto'] == i]['Categoria'].unique())

Produto: LG K10 TV Power
['Celulares']
Produto: Geladeira Duplex
['Eletrodomésticos']
Produto: Lavadora 11 Kg
['Eletrodomésticos']
Produto: Notebook Dell 8 GB
['Eletrônicos']
Produto: Desktop 32 GB
['Eletrônicos']
Produto: Desktop HP 16 GB
['Eletrônicos']
Produto: Micro-Ondas
['Eletrodomésticos']
Produto: Grill
['Eletrodomésticos']
Produto: Forno-Micro-Ondas
['Eletrodomésticos']
Produto: Fritadeira
['Eletroportáteis']
Produto: Ar Condicionado
['Eletrodomésticos']
Produto: Aspirador
['Eletroportáteis']
Produto: Impressora Deskjet
['Eletrônicos']
Produto: Secadora Vapor
['Eletrodomésticos']
Produto: Samsung Galaxy 8
['Celulares']
Produto: Sony Experia XA
['Celulares']
Produto: Morotola Moto G5
['Celulares']
Produto: Ventilador
['Eletroportáteis']
Produto: Processador de Alimentos
['Eletroportáteis']
Produto: Liquidificador
['Eletroportáteis']

Interpretando a coluna "Loja"

In [ ]:
for i in df['Loja'].unique():
  print('Loja '+i)
  print(df[df['Loja'] == i]['Cidade'].unique())

Loja SP8821
['São Paulo']
Loja A9990
['Belo Horizonte']
Loja SP8823
['São Paulo']
Loja R1296
['Rio de Janeiro']
Loja V7654
['Vitória']
Loja P0761
['Cascavel']
Loja SA7761
['Salvador']
Loja SP8822
['São Paulo']
Loja S6543
['Osasco']
Loja B7659
['Campinas']
Loja A9991
['Belo Horizonte']
Loja R1298
['Campos']
Loja R1295
['Rio de Janeiro']
Loja R1297
['Petrópolis']

Portanto, cada código de loja corresponde a um estabelecimento específico.

Interpretando a coluna "Vendedor"

In [ ]:
for i in df['Vendedor'].unique():
  print('Vendedor '+i)
  print(df[df['Vendedor'] == i]['Loja'].unique())

Vendedor Ana Teixeira
['SP8821' 'R1296' 'SP8823' 'V7654' 'A9990' 'SP8822' 'R1297' 'R1295']
Vendedor Josias Silva
['SP8821' 'A9990' 'SP8823' 'R1296' 'V7654' 'P0761' 'SP8822' 'A9991'
 'R1295' 'R1297']
Vendedor Mateus Gonçalves
['SP8821' 'SP8823' 'A9990' 'V7654' 'R1296' 'SP8822' 'P0761' 'A9991'
 'R1297' 'R1295']
Vendedor Artur Moreira
['SP8821' 'SP8823' 'P0761' 'SP8822' 'A9990' 'V7654' 'S6543' 'R1296'
 'A9991' 'R1297' 'R1295']
Vendedor Rodrigo Fagundes
['SP8821' 'A9990' 'SP8823' 'SA7761' 'SP8822' 'P0761' 'V7654' 'R1296'
 'R1297' 'R1295']
Vendedor Fernando Zambrini
['A9990' 'SP8821' 'SP8823' 'V7654' 'R1296' 'SA7761' 'SP8822' 'A9991'
 'R1295']
Vendedor André Pereira
['SP8821' 'SP8823' 'A9990' 'R1296' 'SP8822' 'S6543' 'B7659' 'V7654'
 'SA7761' 'A9991' 'R1298' 'R1295' 'R1297']
Vendedor Maria Fernandes
['SP8821' 'SP8823' 'V7654' 'A9990' 'R1296' 'SP8822' 'S6543' 'A9991'
 'R1298' 'R1295' 'R1297']
Vendedor Aline Sutter
['R1296' 'SP8823' 'SP8821' 'R1295']

Logo, um vendedor pode estar associado a mais de uma loja.

In [ ]:
df.head()

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
0,PROD-001-00,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2012-10-04,679.00,345
1,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-01-01,832.00,712
2,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2,2012-02-02,790.00,390
3,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-03-03,765.32,200
4,PROD-003-02,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Artur Moreira,1004,5,2012-04-04,459.89,234

Verificando se cada vendedor tem um "ID-Vendedor" único, temos:

In [ ]:
for i in df['Vendedor'].unique():
  print('Vendedor '+i)
  print(df[df['Vendedor'] == i]['ID-Vendedor'].unique())

Vendedor Ana Teixeira
[1009]
Vendedor Josias Silva
[1006]
Vendedor Mateus Gonçalves
[1003]
Vendedor Artur Moreira
[1004]
Vendedor Rodrigo Fagundes
[1005]
Vendedor Fernando Zambrini
[1007]
Vendedor André Pereira
[1002]
Vendedor Maria Fernandes
[1001]
Vendedor Aline Sutter
[1008]

Portanto, os vendores tem uma identificação única.

Investigando a coluna "Segmento", temos:

In [ ]:
for i in df['Segmento'].unique():
  print('Segmento '+i)
  print(df[df['Segmento'] == i]['Categoria'].unique())

Segmento Corporativo
['Celulares' 'Eletrônicos']
Segmento Doméstico
['Eletrodomésticos' 'Eletroportáteis' 'Eletrônicos' 'Celulares']
Segmento Industrial
['Eletrodomésticos']

Portanto, a coluna "Segmento" é uma característica do cliente.

Investigando a coluna "Custo", temos:

In [ ]:
for i in df['Produto'].unique():
  print('Produto '+i)
  print(df[df['Produto'] == i]['Custo'].unique())

Produto LG K10 TV Power
[345]
Produto Geladeira Duplex
[712 134 800 400 600 560 790 120]
Produto Lavadora 11 Kg
[390 200 234  90 120]
Produto Notebook Dell 8 GB
[120]
Produto Desktop 32 GB
[120]
Produto Desktop HP 16 GB
[120]
Produto Micro-Ondas
[120]
Produto Grill
[120]
Produto Forno-Micro-Ondas
[120]
Produto Fritadeira
[120]
Produto Ar Condicionado
[120]
Produto Aspirador
[120]
Produto Impressora Deskjet
[120]
Produto Secadora Vapor
[120]
Produto Samsung Galaxy 8
[120]
Produto Sony Experia XA
[120]
Produto Morotola Moto G5
[120]
Produto Ventilador
[120]
Produto Processador de Alimentos
[120]
Produto Liquidificador
[120]

Então, o custo é uma característica da venda do produto.

In [ ]:
df[(df['Produto'] == 'Geladeira Duplex') & (df['Fabricante'] == 'Brastemp')]

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
1,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-01-01,832.00,712
6,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-06-04,1000.91,134
8,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-08-04,1300.00,400
10,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,5,2012-09-04,1287.00,560
11,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,A9990,Belo Horizonte,Minas Gerais,Josias Silva,1006,5,2012-11-04,1651.00,790
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-05-18,1234.00,120
450,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-07-21,800.00,120
452,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-09-23,850.00,120
453,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-10-24,678.00,120
456,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-11-27,1234.00,120

In [ ]:
df.to_excel('Dados_Comerciais_modificado.xlsx', index = False)

#Modelagem de Dados

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('Dados_Comerciais_modificado.xlsx')
df.head(10)

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
0,PROD-001-00,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2012-10-04,679.00,345
1,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-01-01,832.00,712
2,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2,2012-02-02,790.00,390
3,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-03-03,765.32,200
4,PROD-003-02,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Artur Moreira,1004,5,2012-04-04,459.89,234
5,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Rodrigo Fagundes,1005,4,2012-05-04,590.98,90
6,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-06-04,1000.91,134
7,PROD-002-01,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,A9990,Belo Horizonte,Minas Gerais,Fernando Zambrini,1007,2,2012-07-04,1229.00,800
8,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-08-04,1300.00,400
9,PROD-002-01,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,André Pereira,1002,4,2012-09-04,1290.00,600

Para cada atributo, foi verificado o tamanho máximo para definir o tipo de variável no banco de dados do PostgreSQL

In [ ]:
#Verificar o tamanho máximo e mínimo da coluna
# Escolhe a coluna para análise
coluna = 'Fabricante'

# Aplica a função len (comprimento) a cada valor na coluna escolhida
df[coluna] = df[coluna].astype(str) # Converte os valores para string para evitar erros
comprimentos = df[coluna].apply(len)

# Encontra o comprimento mínimo e máximo
minimo = comprimentos.min()
maximo = comprimentos.max()

print(f"Comprimento mínimo na coluna '{coluna}': {minimo}")
print(f"Comprimento máximo na coluna '{coluna}': {maximo}")

Comprimento mínimo na coluna 'Fabricante': 2
Comprimento máximo na coluna 'Fabricante': 10

#Renomeando as Colunas

As colunas devem ser renomeadas para evitar erros no banco de dados e nos algoritmos de inserção de dados no banco de dados do PostgreSQL. Além disso, a alteração da nomenclatura das colunas visa tornar o visual mais profissional.

In [ ]:
df.head(1)

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
0,PROD-001-00,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2012-10-04,679.0,345

In [ ]:
df.rename(columns={'ID-Produto': 'id_produto'}, inplace=True)

In [ ]:
df.rename(columns={'Produto': 'produto'}, inplace=True)

In [ ]:
df.rename(columns={'Categoria': 'categoria'}, inplace=True)

In [ ]:
df.rename(columns={'Segmento': 'segmento'}, inplace=True)

In [ ]:
df.rename(columns={'Fabricante': 'fabricante'}, inplace=True)

In [ ]:
df.rename(columns={'Loja': 'loja'}, inplace=True)

In [ ]:
df.rename(columns={'Cidade': 'cidade'}, inplace=True)

In [ ]:
df.rename(columns={'Estado': 'estado'}, inplace=True)

In [ ]:
df.rename(columns={'Vendedor': 'vendedor'}, inplace=True)

In [ ]:
df.rename(columns={'ID-Vendedor': 'id_vendedor'}, inplace=True)

In [ ]:
df.rename(columns={'Comissão (Percentual)': 'comissao_percentual'}, inplace=True)

In [ ]:
df.rename(columns={'comissao_percentual': 'comissao percentual'}, inplace=True)

In [ ]:
df.rename(columns={'Data Venda': 'data venda'}, inplace=True)

In [ ]:
df.rename(columns={'ValorVenda': 'valor venda'}, inplace=True)

In [ ]:
df.rename(columns={'Custo': 'custo'}, inplace=True)

In [ ]:
df.head(20)

,id_produto,produto,categoria,segmento,fabricante,loja,cidade,estado,vendedor,id_vendedor,comissao percentual,data venda,valor venda,custo
0,PROD-001-00,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2012-10-04,679.00,345
1,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-01-01,832.00,712
2,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2,2012-02-02,790.00,390
3,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-03-03,765.32,200
4,PROD-003-02,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Artur Moreira,1004,5,2012-04-04,459.89,234
5,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Rodrigo Fagundes,1005,4,2012-05-04,590.98,90
6,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-06-04,1000.91,134
7,PROD-002-01,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,A9990,Belo Horizonte,Minas Gerais,Fernando Zambrini,1007,2,2012-07-04,1229.00,800
8,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-08-04,1300.00,400
9,PROD-002-01,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,André Pereira,1002,4,2012-09-04,1290.00,600
10,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,5,2012-09-04,1287.00,560
11,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,A9990,Belo Horizonte,Minas Gerais,Josias Silva,1006,5,2012-11-04,1651.00,790
12,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,4,2012-11-04,1100.00,790
13,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-12-04,1190.00,790
14,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Artur Moreira,1004,2,2012-12-04,1190.98,790
15,PROD-003-02,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,A9990,Belo Horizonte,Minas Gerais,Rodrigo Fagundes,1005,4,2013-01-02,877.00,120
16,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,5,2013-02-02,982.00,120
17,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Fernando Zambrini,1007,6,2013-03-02,872.00,120
18,PROD-003-02,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,5,2013-04-02,799.00,120
19,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,André Pereira,1002,4,2013-05-02,899.00,120

In [ ]:
df.to_excel('Dados_Comerciais_modificado.xlsx', index = False)

#Separando os Dados em Tabelas Diferentes

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Dados_Comerciais_modificado_v2.xlsx')
df.head(10)

,id_produto,produto,categoria,segmento,fabricante,loja,cidade,estado,vendedor,id_vendedor,comissao percentual,data venda,valor venda,custo
0,PROD-001-00,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2012-10-04,679.00,345
1,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-01-01,832.00,712
2,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2,2012-02-02,790.00,390
3,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-03-03,765.32,200
4,PROD-003-02,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Artur Moreira,1004,5,2012-04-04,459.89,234
5,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Rodrigo Fagundes,1005,4,2012-05-04,590.98,90
6,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-06-04,1000.91,134
7,PROD-002-01,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,A9990,Belo Horizonte,Minas Gerais,Fernando Zambrini,1007,2,2012-07-04,1229.00,800
8,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-08-04,1300.00,400
9,PROD-002-01,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,André Pereira,1002,4,2012-09-04,1290.00,600

## Tabela Produto

A tabela produto visa armazenar os dados dos diferentes produtos contidos na base de dados.

In [3]:
df_produto = df[['id_produto', 'produto', 'categoria', 'fabricante']]

In [4]:
df_produto.head(20)

     id_produto           produto         categoria  fabricante
0   PROD-001-00   LG K10 TV Power         Celulares          LG
1   PROD-002-00  Geladeira Duplex  Eletrodomésticos    Brastemp
2   PROD-003-01    Lavadora 11 Kg  Eletrodomésticos    Brastemp
3   PROD-003-01    Lavadora 11 Kg  Eletrodomésticos    Brastemp
4   PROD-003-02    Lavadora 11 Kg  Eletrodomésticos  Electrolux
5   PROD-003-01    Lavadora 11 Kg  Eletrodomésticos    Brastemp
6   PROD-002-00  Geladeira Duplex  Eletrodomésticos    Brastemp
7   PROD-002-01  Geladeira Duplex  Eletrodomésticos  Electrolux
8   PROD-002-00  Geladeira Duplex  Eletrodomésticos    Brastemp
9   PROD-002-01  Geladeira Duplex  Eletrodomésticos  Electrolux
10  PROD-002-00  Geladeira Duplex  Eletrodomésticos    Brastemp
11  PROD-002-00  Geladeira Duplex  Eletrodomésticos    Brastemp
12  PROD-002-00  Geladeira Duplex  Eletrodomésticos    Brastemp
13  PROD-002-00  Geladeira Duplex  Eletrodomésticos    Brastemp
14  PROD-002-00  Geladeira Duplex  Eletrodomésticos    Brastemp
15  PROD-003-02    Lavadora 11 Kg  Eletrodomésticos  Electrolux
16  PROD-003-01    Lavadora 11 Kg  Eletrodomésticos    Brastemp
17  PROD-003-01    Lavadora 11 Kg  Eletrodomésticos    Brastemp
18  PROD-003-02    Lavadora 11 Kg  Eletrodomésticos  Electrolux
19  PROD-003-01    Lavadora 11 Kg  Eletrodomésticos    Brastemp

In [5]:
duplicados = df_produto.duplicated(subset='id_produto', keep='first')

In [6]:
if duplicados.any():
    print(f'Foram encontrados {duplicados.sum()} registros duplicados na coluna "id_produto".')

Foram encontrados 426 registros duplicados na coluna "id_produto".

In [7]:
df_produto.drop_duplicates(subset='id_produto', keep='first', inplace = True)

<ipython-input-7-0d94d90cbb14>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_produto.drop_duplicates(subset='id_produto', keep='first', inplace = True)

In [8]:
df_produto.to_excel('table_produto.xlsx', index = False)

## Tabela Loja

Separando as informações das lojas da base de dados, temos:

In [9]:
df.head()

,id_produto,produto,categoria,segmento,fabricante,loja,cidade,estado,vendedor,id_vendedor,comissao percentual,data venda,valor venda,custo
0,PROD-001-00,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2012-10-04,679.00,345
1,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-01-01,832.00,712
2,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2,2012-02-02,790.00,390
3,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-03-03,765.32,200
4,PROD-003-02,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Artur Moreira,1004,5,2012-04-04,459.89,234

In [10]:
df_loja = df[['loja','cidade','estado']]
df_loja.head(10)

     loja          cidade        estado
0  SP8821       São Paulo     São Paulo
1  SP8821       São Paulo     São Paulo
2  SP8821       São Paulo     São Paulo
3  SP8821       São Paulo     São Paulo
4  SP8821       São Paulo     São Paulo
5  SP8821       São Paulo     São Paulo
6  SP8821       São Paulo     São Paulo
7   A9990  Belo Horizonte  Minas Gerais
8  SP8821       São Paulo     São Paulo
9  SP8821       São Paulo     São Paulo

In [11]:
duplicados = df_loja.duplicated(subset='loja', keep='first')

if duplicados.any():
    print(f'Foram encontrados {duplicados.sum()} registros duplicados na coluna "loja".')
else:
    print('Não foram encontrados valores duplicados!')

Foram encontrados 443 registros duplicados na coluna "loja".

In [12]:
df_loja.drop_duplicates(subset='loja', keep='first', inplace = True)
df_loja.head(20)

<ipython-input-12-1c43d6a936ed>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_loja.drop_duplicates(subset='loja', keep='first', inplace = True)

       loja          cidade          estado
0    SP8821       São Paulo       São Paulo
7     A9990  Belo Horizonte    Minas Gerais
32   SP8823       São Paulo       São Paulo
39    R1296  Rio de Janeiro  Rio de Janeiro
41    V7654         Vitória  Espírito Santo
87    P0761        Cascavel          Paraná
88   SA7761        Salvador           Bahia
103  SP8822       São Paulo       São Paulo
170   S6543          Osasco       São Paulo
173   B7659        Campinas       São Paulo
290   A9991  Belo Horizonte    Minas Gerais
324   R1298          Campos  Rio de Janeiro
345   R1295  Rio de Janeiro  Rio de Janeiro
349   R1297      Petrópolis  Rio de Janeiro

In [13]:
df_loja['loja'].value_counts()

SP8821    1
A9990     1
SP8823    1
R1296     1
V7654     1
P0761     1
SA7761    1
SP8822    1
S6543     1
B7659     1
A9991     1
R1298     1
R1295     1
R1297     1
Name: loja, dtype: int64

In [14]:
df_loja.to_excel('table_loja.xlsx', index = False)

## Tabela Vendedor

In [15]:
df.head()

,id_produto,produto,categoria,segmento,fabricante,loja,cidade,estado,vendedor,id_vendedor,comissao percentual,data venda,valor venda,custo
0,PROD-001-00,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2012-10-04,679.00,345
1,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-01-01,832.00,712
2,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2,2012-02-02,790.00,390
3,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-03-03,765.32,200
4,PROD-003-02,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Artur Moreira,1004,5,2012-04-04,459.89,234

In [16]:
df_vendedor = df[['id_vendedor', 'vendedor']]
df_vendedor.head()

   id_vendedor          vendedor
0         1009      Ana Teixeira
1         1006      Josias Silva
2         1006      Josias Silva
3         1003  Mateus Gonçalves
4         1004     Artur Moreira

In [17]:
duplicados = df_vendedor.duplicated(subset='id_vendedor', keep='first')

if duplicados.any():
    print(f'Foram encontrados {duplicados.sum()} registros duplicados na coluna "id_vendedor".')
else:
    print('Não foram encontrados valores duplicados!')

df_vendedor.drop_duplicates(subset='id_vendedor', keep='first', inplace = True)
df_vendedor.head(20)

Foram encontrados 448 registros duplicados na coluna "id_vendedor".

<ipython-input-17-1d66c701370b>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vendedor.drop_duplicates(subset='id_vendedor', keep='first', inplace = True)

    id_vendedor           vendedor
0          1009       Ana Teixeira
1          1006       Josias Silva
3          1003   Mateus Gonçalves
4          1004      Artur Moreira
5          1005   Rodrigo Fagundes
7          1007  Fernando Zambrini
9          1002      André Pereira
30         1001    Maria Fernandes
39         1008       Aline Sutter

In [18]:
df_vendedor['id_vendedor'].value_counts()

1009    1
1006    1
1003    1
1004    1
1005    1
1007    1
1002    1
1001    1
1008    1
Name: id_vendedor, dtype: int64

In [19]:
df_vendedor.to_excel('table_vendedor.xlsx', index = False)

#Determinando o Lucro das Vendas

In [20]:
import pandas as pd

In [21]:
df = pd.read_excel('/content/Dados_Comerciais_modificado_v2.xlsx')

In [22]:
df.head(10)

,id_produto,produto,categoria,segmento,fabricante,loja,cidade,estado,vendedor,id_vendedor,comissao percentual,data venda,valor venda,custo
0,PROD-001-00,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2012-10-04,679.00,345
1,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-01-01,832.00,712
2,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2,2012-02-02,790.00,390
3,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-03-03,765.32,200
4,PROD-003-02,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Artur Moreira,1004,5,2012-04-04,459.89,234
5,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Rodrigo Fagundes,1005,4,2012-05-04,590.98,90
6,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-06-04,1000.91,134
7,PROD-002-01,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,A9990,Belo Horizonte,Minas Gerais,Fernando Zambrini,1007,2,2012-07-04,1229.00,800
8,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-08-04,1300.00,400
9,PROD-002-01,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,André Pereira,1002,4,2012-09-04,1290.00,600

In [23]:
df['lucro'] = df['valor venda'] - df['custo']

In [24]:
df.head(20)

,id_produto,produto,categoria,segmento,fabricante,loja,cidade,estado,vendedor,id_vendedor,comissao percentual,data venda,valor venda,custo,lucro
0,PROD-001-00,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2012-10-04,679.00,345,334.00
1,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-01-01,832.00,712,120.00
2,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2,2012-02-02,790.00,390,400.00
3,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-03-03,765.32,200,565.32
4,PROD-003-02,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Artur Moreira,1004,5,2012-04-04,459.89,234,225.89
5,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Rodrigo Fagundes,1005,4,2012-05-04,590.98,90,500.98
6,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-06-04,1000.91,134,866.91
7,PROD-002-01,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,A9990,Belo Horizonte,Minas Gerais,Fernando Zambrini,1007,2,2012-07-04,1229.00,800,429.00
8,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-08-04,1300.00,400,900.00
9,PROD-002-01,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,André Pereira,1002,4,2012-09-04,1290.00,600,690.00
10,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,5,2012-09-04,1287.00,560,727.00
11,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,A9990,Belo Horizonte,Minas Gerais,Josias Silva,1006,5,2012-11-04,1651.00,790,861.00
12,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,4,2012-11-04,1100.00,790,310.00
13,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-12-04,1190.00,790,400.00
14,PROD-002-00,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Artur Moreira,1004,2,2012-12-04,1190.98,790,400.98
15,PROD-003-02,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,A9990,Belo Horizonte,Minas Gerais,Rodrigo Fagundes,1005,4,2013-01-02,877.00,120,757.00
16,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,5,2013-02-02,982.00,120,862.00
17,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Fernando Zambrini,1007,6,2013-03-02,872.00,120,752.00
18,PROD-003-02,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,5,2013-04-02,799.00,120,679.00
19,PROD-003-01,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,André Pereira,1002,4,2013-05-02,899.00,120,779.00

In [25]:
df.to_excel('Dados_Comerciais_modificado_v3.xlsx', index = False)